export const PATH = {
    USERS: {
        REGISTER_FREElANCER: "auth/freelancer/register",
        REGISTER_CLIENT: "auth/client/register",
        USER_LOGOUT: "auth/user/logout",
        USER_LOGIN: "auth/user/login",
        GET_INFO_FREELANCER: "auth/freelancer/profile",
        GET_INFO_CLIENT: "auth/client/profile",
        GET_INFO_USER: "auth/user/profile",
        GET_All_CLIENT: "auth/client/all",
        GET_ALL_FREELANCER: "auth/freelancer/all",
        GET_ALL_USER: "auth/user/all",
        ADD_DESCRIPTION: "auth/user/description/add",
        EDIT_DESCRIPTION: "auth/user/description/edit",
    },
    OFFERS: {
        CREATE_FREELANCER: "offer/freelancer/create",
        CREATE_CLIENT: "offer/client/create",
        EDIT_CLIENT: "offer/client/edit",
        DELETE_CLIENT: "offer/client/delete",
        DELETE_FREELANCER: "offer/freelancer/delete",
        EDIT_FREELANCER: "offer/freelancer/edit",
        GET_ONE_CLIENT: "offer/client",
        GET_ONE_FREELANCER: "offer/freelancer",
        GET_All_FREELANCER: "offer/freelancer/all",
        GET_ALL_CLIENTS: "offer/client/all",
        APPLY_CLIENT_OFFER: "offer/client/apply",
        DECLINE_FREELANCER: "offer/client/decline",
        DECLINE_CLIENT: "offer/freelancer/decline",
        SEND_MESSAGE: "offer/freelancer/send",
    },
};
